In [19]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [20]:
import numpy as np
import torch

In [21]:
A = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
A

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [22]:
# A diagonal matrix
D = torch.diag(torch.tensor([-1, 2, 1]))
D

tensor([[-1,  0,  0],
        [ 0,  2,  0],
        [ 0,  0,  1]])

In [23]:
D @ A

tensor([[-1, -2, -3],
        [ 8, 10, 12],
        [ 7,  8,  9]])

In [24]:
scaling_vector = torch.tensor([-1, 2, 1])
scaled_A = A * scaling_vector
scaled_A

tensor([[-1,  4,  3],
        [-4, 10,  6],
        [-7, 16,  9]])

In [25]:
d1, d2 = 3, 4
example_tens = torch.arange(d1 * d2).reshape(d1, d2)
example_tens

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [26]:
base_vect = torch.tensor([1, 1, 1, 1])
base_vect

tensor([1, 1, 1, 1])

In [27]:
example_tens.unsqueeze(0)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]])

In [28]:
print(example_tens.unsqueeze(0).shape)

torch.Size([1, 3, 4])


In [29]:
example_tens_dim = example_tens.unsqueeze(1)
example_tens_dim

tensor([[[ 0,  1,  2,  3]],

        [[ 4,  5,  6,  7]],

        [[ 8,  9, 10, 11]]])

In [30]:
print(example_tens_dim.shape)

torch.Size([3, 1, 4])


In [31]:
example_tens = torch.arange(d1 * d2).reshape(d1, d2)
example_tens

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [32]:
example_tens_scaled = example_tens.unsqueeze(-1) * base_vect.unsqueeze(0).unsqueeze(0)
example_tens_scaled

tensor([[[ 0,  0,  0,  0],
         [ 1,  1,  1,  1],
         [ 2,  2,  2,  2],
         [ 3,  3,  3,  3]],

        [[ 4,  4,  4,  4],
         [ 5,  5,  5,  5],
         [ 6,  6,  6,  6],
         [ 7,  7,  7,  7]],

        [[ 8,  8,  8,  8],
         [ 9,  9,  9,  9],
         [10, 10, 10, 10],
         [11, 11, 11, 11]]])

In [33]:
example_tens_scaled[0]  # The first sequence, embedded

tensor([[0, 0, 0, 0],
        [1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]])

In [34]:
example_tens_scaled[0, 0]  # The first sequence, first element

tensor([0, 0, 0, 0])

In [35]:
example_tens_scaled[:, 0, :]  # The first batch (as an embedded sequence)

tensor([[0, 0, 0, 0],
        [4, 4, 4, 4],
        [8, 8, 8, 8]])

In [ ]:
from embedding import PotentialSpinEncoding

enc = PotentialSpinEncoding(4, 3, test_init_base=base_vect.to(dtype=torch.float32))
example_embedded = enc(example_tens, example_tens)
example_embedded

tensor([[[ 0.,  0.,  0.,  0.],
         [ 1.,  1.,  1.,  1.],
         [ 2.,  2.,  2.,  2.],
         [ 3.,  3.,  3.,  3.]],

        [[ 4.,  4.,  4.,  4.],
         [ 5.,  5.,  5.,  5.],
         [ 6.,  6.,  6.,  6.],
         [ 7.,  7.,  7.,  7.]],

        [[ 8.,  8.,  8.,  8.],
         [ 9.,  9.,  9.,  9.],
         [10., 10., 10., 10.],
         [11., 11., 11., 11.]],

        [[ 0.,  0.,  0.,  0.],
         [ 1.,  1.,  1.,  1.],
         [ 2.,  2.,  2.,  2.],
         [ 3.,  3.,  3.,  3.]],

        [[ 4.,  4.,  4.,  4.],
         [ 5.,  5.,  5.,  5.],
         [ 6.,  6.,  6.,  6.],
         [ 7.,  7.,  7.,  7.]],

        [[ 8.,  8.,  8.,  8.],
         [ 9.,  9.,  9.,  9.],
         [10., 10., 10., 10.],
         [11., 11., 11., 11.]]], grad_fn=<CatBackward0>)